version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is in db folder
  db:
      build: db/.
      command: --default-authentication-plugin=mysql_native_password
      restart: always
    #image: mysql:8.3
   # environment:
   #   MYSQL_ROOT_PASSWORD: my-secret-pw
   #   MYSQL_DATABASE: world
   # volumes:
      #  - ./db/world.sql:/docker-entrypoint-initdb.d/world.sql
   # ports:
    #  - "3306:3306"