# GitHub Actions Workflow for the Population Reporting System
# This workflow is triggered on every push to the repository
name: A workflow for the population reporting system
on: push

jobs:
  build:
    name: Population Reporting System Action
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 for the Java project
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn package

      # Step 4: Run Docker Compose to build and start containers
      - name: Run Docker Compose
        run: |
          docker compose up --abort-on-container-exit
