name: A workflow for the population reporting system
on: push

jobs:
  build:
    name: Population Reporting System Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Image
        run: docker build -t prsimage .
      - name: Run image
        run: docker run --name prscontainer -d prsimage
      - name: view logs
        run: docker logs prscontainer
